name: dbt CI

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ main ]

jobs:
  dbt-build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dbt
        run: |
          pip install dbt-snowflake

      - name: Debug secrets
        run: |
          echo "DBT_USER=${DBT_USER}"
          echo "DBT_ACCOUNT=${DBT_ACCOUNT}"
          echo "DBT_PASSWORD is set? ${#DBT_PASSWORD}"

      - name: Create dbt profile
        env:
          DBT_USER: ${{ secrets.DBT_USER }}
          DBT_PASSWORD: ${{ secrets.DBT_PASSWORD }}
          DBT_ACCOUNT: ${{ secrets.DBT_ACCOUNT }}
        run: |
          mkdir -p ~/.dbt
          cat <<EOF > ~/.dbt/profiles.yml
          default:
            target: dev
            outputs:
              dev:
                type: snowflake
                account: $DBT_ACCOUNT
                user: $DBT_USER
                password: $DBT_PASSWORD
                role: ACCOUNTADMIN
                database: DBT_SFDB
                warehouse: COMPUTE_WH
                schema: ANALYTICS_DEV
                threads: 4
          EOF

      - name: Clean dbt
        run: dbt clean --profiles-dir ~/.dbt

      - name: Remove old dbt state
        run: |
          rm -rf target
          rm -rf dbt_packages
          rm -rf logs

      - name: Debug dbt source resolution
        run: |
          dbt ls --resource-type source --profiles-dir ~/.dbt --project-dir .


      - name: Run dbt build (DEV)
        env:
          DBT_USER: ${{ secrets.DBT_USER }}
          DBT_PASSWORD: ${{ secrets.DBT_PASSWORD }}
          DBT_ACCOUNT: ${{ secrets.DBT_ACCOUNT }}
        run: |
          dbt deps
          dbt build --profiles-dir ~/.dbt --target dev
